### ISSUE TITLE
Can't Add Mods + Can't Assign Directory

### ISSUE THREAD

**Issue by CFlatFlat** [gurrenm3/BTD-Mod-Loader#3]
I can't seem to add mods. I'm pretty sure I made the ZIP folders are correctly, but they don't show up and there's no "browse" option (it's in the same folder as the application, I've also tried the "Mods" folder but that doesn't work either).

Also, when I assign the directory, it just tells me that it's not assigned again.

I am using 1.7.1

![temp](https://user-images.githubusercontent.com/58796562/70675864-624af200-1c58-11ea-9ba9-0403009f7755.PNG)

**Comment by gurrenm3** [comment]
This issue has been fixed
